# Generated by glovebox - DO NOT EDIT DIRECTLY
#
# To modify:
#   glovebox add <snippet>      Add a snippet
#   glovebox remove <snippet>   Remove a snippet
#   glovebox build              Regenerate this file
#
# Snippets included:
#   - base
#   - fish
#   - neovim
#   - tmux
#   - mise
#   - nodejs
#   - claude-code
#   - gemini-cli
#   - opencode

FROM ubuntu:24.04

# Avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Add APT repositories
RUN apt-add-repository ppa:fish-shell/release-4

# Install packages
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    build-essential \
    software-properties-common \
    unzip \
    ca-certificates \
    gnupg \
    sudo \
    jq \
    libffi-dev \
    libyaml-dev \
    fish \
    tmux \
    python3 \
    python3-pip \
    pipx \
    && rm -rf /var/lib/apt/lists/*

# base setup (root)
RUN <<'EOF'
set -e
# Configure the ubuntu user (UID 1000, already exists in ubuntu:24.04)
echo "ubuntu ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/ubuntu
chmod 0440 /etc/sudoers.d/ubuntu
mkdir -p /home/ubuntu/.local/bin
chown -R ubuntu:ubuntu /home/ubuntu
EOF

# fish setup (root)
RUN <<'EOF'
set -e
usermod -s /usr/bin/fish ubuntu
mkdir -p /home/ubuntu/.config/fish
chown -R ubuntu:ubuntu /home/ubuntu/.config/fish
EOF

# neovim setup (root)
RUN <<'EOF'
set -e
ARCH=$(dpkg --print-architecture)
if [ "$ARCH" = "amd64" ]; then
    NVIM_ARCH="linux-x86_64"
elif [ "$ARCH" = "arm64" ]; then
    NVIM_ARCH="linux-arm64"
else
    echo "Unsupported architecture: $ARCH" && exit 1
fi
curl -fsSL -o nvim.tar.gz "https://github.com/neovim/neovim/releases/latest/download/nvim-${NVIM_ARCH}.tar.gz"
tar -C /opt -xzf nvim.tar.gz
rm nvim.tar.gz
ln -s /opt/nvim-${NVIM_ARCH}/bin/nvim /usr/local/bin/nvim
EOF

# tmux setup (root)
RUN <<'EOF'
set -e
pipx install tmuxp
mkdir -p /home/ubuntu/.local/bin
chown -R ubuntu:ubuntu /home/ubuntu/.local
EOF

# mise setup (root)
RUN <<'EOF'
set -e
curl https://mise.run | MISE_INSTALL_PATH=/usr/local/bin/mise sh
mkdir -p /home/ubuntu/.local/share/mise
chown -R ubuntu:ubuntu /home/ubuntu/.local/share/mise
EOF

# nodejs setup (root)
RUN <<'EOF'
set -e
curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt-get install -y nodejs
rm -rf /var/lib/apt/lists/*
EOF

# claude-code setup (root)
RUN <<'EOF'
set -e
npm install -g @anthropic-ai/claude-code
mkdir -p /home/ubuntu/.anthropic
chown -R ubuntu:ubuntu /home/ubuntu/.anthropic
EOF

# gemini-cli setup (root)
RUN <<'EOF'
set -e
npm install -g @google/gemini-cli
mkdir -p /home/ubuntu/.config/gemini
chown -R ubuntu:ubuntu /home/ubuntu/.config/gemini
EOF

# opencode setup (root)
RUN <<'EOF'
set -e
npm install -g opencode-ai
EOF

# Copy and set up entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 755 /usr/local/bin/entrypoint.sh

# Switch to non-root user
USER ubuntu
WORKDIR /home/ubuntu

# Environment variables
ENV EDITOR=nvim
ENV SHELL=/usr/bin/fish

# Ensure local binaries are in PATH
ENV PATH="/home/ubuntu/.local/bin:/usr/local/bin:$PATH"

# Set working directory for mounted projects
WORKDIR /workspace

# Use entrypoint to fix permissions on mounted volumes
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/bin/fish"]
